### ISSUE TITLE
Create new session bug

### ISSUE THREAD

**Issue by Rollagit** [thedemons/opentele#123]
Traceback (most recent call last):
  File "/root/1/opentele/1.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/1/opentele/1.py", line 15, in main
    tdesk = await client.ToTDesktop(flag=CreateNewSession)
NameError: name 'CreateNewSession' is not defined

**Comment by to4no4sv** [comment]
from opentele.api import CreateNewSession
