### ISSUE TITLE
No account has been loaded

### ISSUE THREAD

**Issue by Dog-Feng** [thedemons/opentele#128]
I use the example program to run and get an error

Traceback (most recent call last):
  File "D:\app\PyCharm 2024.1.2\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\PyCharm 2024.1.2\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 243, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "D:\python\Lib\asyncio\futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "D:\python\Lib\asyncio\tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "D:\project\moonbix-bot-main\tdata.py", line 10, in main
    tdesk = TDesktop(tdataFolder)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\td\tdesktop.py", line 141, in __init__
    self.LoadTData()
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\td\tdesktop.py", line 216, in LoadTData
    raise e
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\td\tdesktop.py", line 203, in LoadTData
    self.__loadFromTData()
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\td\tdesktop.py", line 453, in __loadFromTData
    Expects(len(self.accounts) > 0, "No account has been loaded")
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\exception.py", line 326, in Expects
    raise exception
  File "D:\project\BlumClicker-main\.venv\Lib\site-packages\opentele\td\tdesktop.py", line 453, in __loadFromTData
    Expects(len(self.accounts) > 0, "No account has been loaded")
opentele.exception.OpenTeleException: Unexpected Exception: No account has been loaded [ Called by BaseObject.TDesktop.__loadFromTData() ]

Does anyone know what the problem is?

**Comment by amao12580** [comment]
same issue

**Comment by anikin-io** [comment]
same issue +

**Comment by Gr0myx** [comment]
same issue

**Comment by Just-Bax** [comment]
Solution: https://github.com/thedemons/opentele/issues/79#issuecomment-2211670877

```
pip uninstall opentele -y
pip install git+https://github.com/thedemons/opentele.git
```
