### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by drdoof2019** [thedemons/opentele#63]
Hello,
I am using ".session to tdata" feature. 
But it gives error:
```
Traceback (most recent call last):
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019F5C6B1CF0>
Traceback (most recent call last):
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\honur\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
I think its something about async but could not figure it out. Can you help?

**Comment by Nathan6103** [comment]
same

**Comment by jhemmmm** [comment]
This can be solve by adding
`asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`

**Comment by whatislove14** [comment]
> Where should I write?

before asyncio.run()
in other words - before starting the program
