### ISSUE TITLE
{Bug}

### ISSUE THREAD

**Issue by lolminerxmrig** [thedemons/opentele#73]
Hi.
can help Fixed

'C:\Users\Administrator\Downloads\Compressed\Telegram-noborderz-main\Telegram-noborderz-main\sessions>1.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\Telegram-noborderz-main\Telegram-noborderz-main\sessions\1.py", line 29, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Downloads\Compressed\Telegram-noborderz-main\Telegram-noborderz-main\sessions\1.py", line 10, in main
    tdesk = TDesktop(tdataFolder)
  File "C:\Python310\lib\site-packages\opentele\td\tdesktop.py", line 141, in __init__
    self.LoadTData()
  File "C:\Python310\lib\site-packages\opentele\td\tdesktop.py", line 216, in LoadTData
    raise e
  File "C:\Python310\lib\site-packages\opentele\td\tdesktop.py", line 203, in LoadTData
    self.__loadFromTData()
  File "C:\Python310\lib\site-packages\opentele\td\tdesktop.py", line 453, in __loadFromTData
    Expects(len(self.accounts) > 0, "No account has been loaded")
  File "C:\Python310\lib\site-packages\opentele\exception.py", line 326, in Expects
    raise exception
  File "C:\Python310\lib\site-packages\opentele\td\tdesktop.py", line 453, in __loadFromTData
    Expects(len(self.accounts) > 0, "No account has been loaded")
opentele.exception.OpenTeleException: Unexpected Exception: No account has been loaded [ Called by BaseObject.TDesktop.__loadFromTData() ]'

**Comment by jhemmmm** [comment]
I am having the same issue.

**Comment by thedemons** [comment]
Patched in [this PR](https://github.com/thedemons/opentele/pull/74)
